Import('*')

# Local includes
env.Append(CPPPATH = ['#'])

p1 = env.Program('JSON', 'JSON.cpp');
p2 = env.Program('JSONDefault', 'JSONDefault.cpp');
p3 = env.Program('Observable', 'Observable.cpp');

Return('p1 p2 p3')
