language: cpp
compiler: gcc
sudo: false

env:
  - DEBUG_BUILD=1
  - DEBUG_BUILD=0

script:
  - scons debug=$DEBUG_BUILD -j 4

addons:
  apt:
    sources:
      - mariadb-10.0

    packages:
      - scons
      - libbz2-dev
      - zlib1g-dev
      - libexpat1-dev
      - libssl-dev
      - libboost-iostreams-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-regex-dev
      - libsqlite3-dev
      - libv8-dev
      - binutils-dev
      - libmariadbclient-dev
