language: cpp
compiler: gcc
dist: xenial

env:
  - DEBUG_BUILD=1
  - DEBUG_BUILD=0

script:
  - scons debug=$DEBUG_BUILD -j 4

addons:
  apt:
    packages:
      - scons
      - libssl-dev
      - libv8-dev
      - binutils-dev
