Import('*')

# Local includes
env.Append(CPPPATH = ['#'])

p1 = env.Program('hmac-sha256-aws-s3', 'hmac-sha256-aws-s3.cpp')
p2 = env.Program('readkey',            'readkey.cpp')
p3 = env.Program('sha256',             'sha256.cpp')

Return('p1 p2 p3')
