import os

env = Environment(ENV = os.environ,
                  TARGET_ARCH = os.environ.get('TARGET_ARCH', 'x86'))
env.Tool('config', toolpath = [Dir('#/..')])
env.CBLoadTools('compiler cbang', paths = [str(Dir('#/..'))])
conf = env.CBConfigure()

# Build Info
env.CBLoadTool('build_info')
env.Replace(BUILD_INFO_NS = 'cb::BuildInfo')

# Configure
if not env.GetOption('clean'):
    conf.CBConfig('compiler')
    conf.CBConfig('cbang')
    env.CBDefine('USING_CBANG') # Using CBANG macro namespace

# Test
Export('env')

def set_enabled(test, enabled):
    # Toggle the testHarness 'disable' marker based on feature availability
    for t in Glob('%s/*Test' % test):
        disable = '%s/disable' % t
        if enabled:
            try: os.unlink(disable)
            except OSError: pass
        elif not os.path.exists(disable): open(disable, 'w').close()

tests = []
for test in Glob('*Tests'):
    script = str(test) + '/SConscript'
    if not os.path.exists(script): continue
    name = str(test)

    if name in ('cryptoTests', 'iostreamTests', 'serverTests'):
        enabled = env.CBConfigEnabled('openssl')
    elif name == 'dbTests': enabled = env.CBConfigEnabled('mariadb')
    else: enabled = True

    set_enabled(name, enabled)
    if enabled: tests.append(SConscript(script))

conf.Finish()

test = Command('test', '', './testHarness')
Depends(test, tests)

Default(tests)
Clean(tests, test)
