import os
import re
from SCons.Script import *

Import('*')

env = env.Clone()

# Remove warnings
import re
pat = r'-W((all)|(error)|(suggest-override))(=[^\s$]+)?(\s|$)'
env.Replace(CCFLAGS = re.sub(pat, '', env.subst('${CCFLAGS}')))
env.Replace(CXXFLAGS = re.sub(pat, '', env.subst('${CXXFLAGS}')))

# Build boost lib
src = []
for lib in ['iostreams', 'filesystem', 'system']:
    src += Glob('libs/%s/src/*.cpp' % lib)

lib = env.Library('#/lib/cbang-boost', src)

Return('lib')
